[tool.poetry]
name = "my-hw-e-commerce"
version = "0.1.0"
description = ""
authors = ["Lada Anpilogova <lada2fox@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
